## Extracting the weights of the network

In [ ]:
model.get_weights()

[array([[-1.51, -2.14, 2.22, -0.58, -0.46],
        [1.88, 2.40, -1.17, 0.04, -0.60]], dtype=float32),
 array([0.31, 0.53, 0.74, -0.04, 0.00], dtype=float32),
 array([[3.12],
        [3.33],
        [-2.11],
        [-0.38],
        [-0.33]], dtype=float32),
 array([-1.23], dtype=float32)]

## Extracting the output of the first layer

In [ ]:
list(map(lambda x: x.name, model.layers))

['dense', 'dense_1']

In [ ]:
"""Keras function for getting the output of a given layer
This function is created acording to the layer_indexthe function works in the following way
Input: entry data of the neuron 
Output: output of the network  
The function below works for the input neuron  """
layer_index = 0
output_function = K.function([model.layers[0].input], model.get_layer(index=layer_index).output)

In [ ]:
#Testing the function with the previous data 
layer_output = output_function([test_X])  # input_data is a numpy array
print(layer_output)

[[0.53 0.80 0.72 0.00 0.00]
 [0.61 0.85 0.93 0.00 0.00]
 [0.00 0.00 1.73 0.00 0.00]
 [0.00 0.00 2.06 0.00 0.00]]
